# VHS tape for setup clai demos
# Install: brew install charmbracelet/tap/vhs
# Source from demo tapes

# Set Shell "bash"
Set FontSize 20
Set Width 1200
Set Height 600
# Set Theme "Catppuccin Mocha"
Set Padding 20
Set TypingSpeed 70ms
# Set Framerate 30
# Set BorderRadius 10
# Set Margin 20
# Set MarginFill "#151b23"
# Set CursorBlink false

Hide
Type "cd assets"
Enter
Sleep 500ms
Ctrl+L
Show

Sleep 1s
